# Generated by Django 5.0.7 on 2024-07-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('account_status', models.FloatField(verbose_name='account status')),
                ('account_credit', models.FloatField(blank=True, verbose_name='account credit')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
