# Generated by Django 5.0.7 on 2024-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_credit',
            field=models.FloatField(default=0, verbose_name='account credit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_status',
            field=models.FloatField(default=0, verbose_name='account status'),
        ),
    ]
