# Generated by Django 5.0.7 on 2024-07-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_status_alter_client_account_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='account_credit',
            new_name='abono',
        ),
    ]
