# Generated by Django 5.0.7 on 2024-07-29 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_client_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='abono',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='abono'),
        ),
    ]
