# Generated by Django 5.0.7 on 2024-07-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stored_Product_Record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooked_equino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_shrink', models.FloatField(max_length=3, verbose_name='merma')),
                ('product_raw', models.FloatField(max_length=5, verbose_name='product row')),
                ('product_cooked', models.FloatField(max_length=5, verbose_name='product cooked')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('id_product_reguistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stored_Product_Record.product_registration', verbose_name='product reguister')),
            ],
            options={
                'verbose_name': 'Cooked_equino',
                'verbose_name_plural': 'Cooked_equinos',
            },
        ),
    ]
