# Generated by Django 5.0.7 on 2024-07-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchen', '0002_remove_cooked_equino_id_product_reguistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooked_equino',
            name='status',
            field=models.BooleanField(default=False, verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='cooked_equino',
            name='estimated_shrink',
            field=models.FloatField(max_length=3, verbose_name='shrink'),
        ),
        migrations.AlterField(
            model_name='cooked_equino',
            name='product_cooked',
            field=models.FloatField(max_length=5, verbose_name='expected loss of knowledge'),
        ),
        migrations.AlterField(
            model_name='cooked_equino',
            name='product_raw',
            field=models.FloatField(max_length=5, verbose_name='product raw'),
        ),
    ]
