# Generated by Django 5.0.7 on 2024-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchen', '0003_cooked_equino_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooked_equino',
            name='estimated_shrink',
            field=models.CharField(choices=[('0.4', '40%')], default='0.4', max_length=3, verbose_name='shrink'),
        ),
        migrations.AlterField(
            model_name='cooked_equino',
            name='product',
            field=models.CharField(choices=[('TRE', 'Tripa Equino')], default='TRE', max_length=3, verbose_name='product'),
        ),
    ]
