# Generated by Django 5.0.7 on 2024-07-29 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchen', '0004_alter_cooked_equino_estimated_shrink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooked_equino',
            name='product_cooked',
            field=models.FloatField(blank=True, max_length=5, verbose_name='expected loss of knowledge'),
        ),
        migrations.AlterField(
            model_name='cooked_equino',
            name='product_raw',
            field=models.FloatField(max_length=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='product raw'),
        ),
    ]
