# Generated by Django 5.0.7 on 2024-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cell',
            field=models.IntegerField(verbose_name='cell'),
        ),
    ]
