# Generated by Django 5.0.7 on 2024-07-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=6, verbose_name='amount')),
                ('unit', models.CharField(choices=[('KG', 'kilogramo'), ('PZ', 'prize')], default='KG', max_length=2, verbose_name='unit')),
                ('price', models.FloatField(max_length=4, verbose_name='price')),
                ('total', models.FloatField(max_length=6, verbose_name='total')),
                ('state', models.BooleanField(default=False, verbose_name='state')),
                ('id_produc_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product_shop', verbose_name='product')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Product_registration',
                'verbose_name_plural': 'Product_registrations',
            },
        ),
    ]
