# Generated by Django 5.0.7 on 2024-07-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stored_Product_Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_registration',
            name='total',
            field=models.FloatField(blank=True, max_length=6, verbose_name='total'),
        ),
    ]
