# Generated by Django 5.0.7 on 2024-07-27 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stored_Product_Record', '0002_alter_product_registration_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_registration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_registration',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='product_registration',
            name='amount',
            field=models.FloatField(max_length=7, verbose_name='amount'),
        ),
    ]
