# Generated by Django 5.0.7 on 2024-07-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stored_Product_Record', '0003_product_registration_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_registration',
            name='unit',
            field=models.CharField(choices=[('KG', 'kilogramo'), ('PZ', 'pieza')], default='KG', max_length=2, verbose_name='unit'),
        ),
    ]
