# Generated by Django 5.0.7 on 2024-07-29 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stored_Product_Record', '0004_alter_product_registration_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_registration',
            name='amount',
            field=models.FloatField(max_length=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='product_registration',
            name='price',
            field=models.FloatField(max_length=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
