# Generated by Django 5.0.7 on 2024-07-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Stored_Product_Record', '0004_alter_product_registration_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_shop',
            new_name='Product_purchase',
        ),
    ]
