# Generated by Django 5.0.7 on 2024-07-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_product_shop_product_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_purchase',
            options={'verbose_name': 'Product_purchase', 'verbose_name_plural': 'Product_purchases'},
        ),
    ]
