# Generated by Django 5.0.7 on 2024-07-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=6, verbose_name='amount')),
                ('previous_credit', models.FloatField(max_length=6, verbose_name='previous credit')),
                ('total', models.FloatField(max_length=6, verbose_name='total')),
                ('account_credit', models.FloatField(blank=True, verbose_name='account credit')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client', verbose_name='Client')),
                ('id_product_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product_sale', verbose_name='Product sale')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
