# Generated by Django 5.0.7 on 2024-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='previous_credit',
            field=models.FloatField(default=0, max_length=6, verbose_name='previous credit'),
        ),
    ]
