# Generated by Django 5.0.7 on 2024-07-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Sale', '0003_alter_note_amount_alter_note_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='account_credit',
            field=models.FloatField(blank=True, default=0, verbose_name='account credit'),
        ),
    ]
