# Generated by Django 5.0.7 on 2024-07-29 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_Sale', '0004_alter_note_account_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='amount',
            field=models.FloatField(default=0, max_length=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
    ]
